### ISSUE TITLE
Execute db-user-uuid-init.sql fails

### ISSUE THREAD

**Issue by eingress** [elitan/hasura-backend-plus#49]
Attempt to Hasura > Data > Run SQL with **db-user-uuid-init.sql** fails with the following error:

`SQL Execution Failed
postgres-error : function public.set_current_timestamp_updated_at() does not exist`

Looks like this trigger function is simply missing from the dump.

**Comment by elitan** [comment]
The `db-user-uuid-init.sql` script is meant to run as a postgres init script.

Ex like this for docker compose:

```
version: '3.6'
services:
  postgres:
    image: postgres:11.5
    restart: always
    volumes:
    - ./db_data:/var/lib/postgresql/data
    - ./db-user-uuid-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
    - "5432:5432"
```

and that works with the previous update. However, it does not work copy and paste the SQL code in the Run SQL` in the Hasura console, like you tried. I'll see if I can find out why.

I get the error: 
> SQL Execution Failed
> function does not return a "COMPOSITE" type
