### ISSUE TITLE
add self hosted s3 like Minio.io

### ISSUE THREAD

**Issue by mnlbox** [elitan/hasura-backend-plus#9]
Hi @elitan,
Now this repo support AWS s3 or DigitalOcean space I think some self hosted s3 implementation like Minio.io also can useful.
Just take a look at this:
https://www.minio.io/

**Comment by elitan** [comment]
Absolutely. I think this is already possible. Just make sure the S3-related environment variables are correct and you should be able to use any s3 compatible block storage service.

**Comment by mnlbox** [comment]
So is it possible now? Can you provide some example about this?

**Comment by elitan** [comment]
Check out here:

https://github.com/minio/minio/issues/4769#issuecomment-331033735

I'll leave this issue open until something more useful is written.

But I am 99% sure that is possible to add a minio service and use it as instead of S3 och DO Spaces. It should just be a matter of environment variables in hasura-backend-plus.

**Comment by mnlbox** [comment]
@elitan Are you have time to check hb+ with Minio?

**Comment by elitan** [comment]
HB+ with MINIO is working now. Confirmed.

Here is an example:

```
  176cb9a8-hasura-backend-plus:
    image: 'elitan/hasura-backend-plus:v0.0.6-alpha'
    restart: always
    environment:
      PORT: 3000
      HASURA_GQE_ENDPOINT: 'https://hasura-176cb9a8.nhost.io/v1alpha1/graphql'
      HASURA_GQE_ADMIN_SECRET: 676f3291726d524ff4150024d79de68d
      HASURA_GQE_JWT_SECRET: >-
        {"type":"HS256", "key":
        "ba12ce8a2efde1301c3a8e63868725bc0927e7e369af0443fc8a17376486e6e8317d1cfb5229b668ddfeb5f14bd91f283eb0b4460c212fcc816b8e73de13bad3"}
      USER_FIELDS: ''
      S3_ACCESS_KEY_ID: 31f90048503ead6187d4e2ebf313c3f9
      S3_SECRET_ACCESS_KEY: 6577e9380e3cb6172512bdd48490f038714724e0fbcd3cd21dd8ac6a4b661683
      S3_ENDPOINT: minio-176cb9a8.nhost.io
      S3_BUCKET: nhost
      DOMAIN: backend-176cb9a8.nhost.io
      REFETCH_TOKEN_EXPIRES: 54000
    volumes:
      - './storage/rules:/app/src/storage/rules'
  176cb9a8-minio:
    image: minio/minio
    restart: always
    volumes:
      - '/mnt/minio_volume/123-176cb9a8/data:/export'
      - '/mnt/minio_volume/123-176cb9a8/config:/root/.minio'
    environment:
      MINIO_ACCESS_KEY: 31f90048503ead6187d4e2ebf313c3f9
      MINIO_SECRET_KEY: 6577e9380e3cb6172512bdd48490f038714724e0fbcd3cd21dd8ac6a4b661683
    entrypoint: sh
    command: '-c ''mkdir -p /export/nhost && /usr/bin/minio server /export'''
```
